import { signIn } from "next-auth/react";
import Head from "next/head";
import { FormEvent, ReactElement } from "react";
import { NextPageWithLayout } from "./_app";

const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
  event.preventDefault();

  const email = ( event.currentTarget.elements.namedItem("email") as HTMLInputElement ).value;
  const password = ( event.currentTarget.elements.namedItem("password") as HTMLInputElement ).value;

  signIn("credentials", { email, password, callbackUrl: "/dashboard" });
};

const Home: NextPageWithLayout = () => {

  return (
    <div>
      <Head>
        <title>Nextjs SSR session Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row items-center justify-center min-h-screen">
        <div>
          <h1>
            Log in to your account
          </h1>
          <div>
            <form onSubmit={handleSubmit}>
              <div>
                <label>Email</label>
                <input
                  name="email"
                  type="email"
                  placeholder="Enter your email"
                  required
                />
              </div>
              <div>
                <label>Password</label>
                <input
                  name="password"
                  type="password"
                  placeholder="Enter your password"
                  required
                />
              </div>
              <button>
                Log in
              </button>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return page;
};

Home.skipAuth = true;

export default Home;
